// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZDxVqlvt66CLSHLqr2xcgkeKX7apLD2A',
    appId: '1:205126384896:web:8a71aeb85ac3dd5388c7e5',
    messagingSenderId: '205126384896',
    projectId: 'push-notification-8c37c',
    authDomain: 'push-notification-8c37c.firebaseapp.com',
    storageBucket: 'push-notification-8c37c.appspot.com',
    measurementId: 'G-0SGFKRT88E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADMW0d0zWrB93RSwg0uXBAF602t76Zaks',
    appId: '1:205126384896:android:f799ed0ee629c7d088c7e5',
    messagingSenderId: '205126384896',
    projectId: 'push-notification-8c37c',
    storageBucket: 'push-notification-8c37c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9li6nab6YNYk2uPvJX-vXMV2O2bzSlSE',
    appId: '1:205126384896:ios:c3ce26847c4fda9e88c7e5',
    messagingSenderId: '205126384896',
    projectId: 'push-notification-8c37c',
    storageBucket: 'push-notification-8c37c.appspot.com',
    iosBundleId: 'com.example.pushnotification',
  );
}
